apiVersion: v1
kind: Namespace
metadata:
  name: vault

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault
  namespace: vault

---

apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  ports:
    - port: 8200
      targetPort: 8200
  selector:
    app: vault

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault-0
  namespace: vault
spec:
  serviceName: vault
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault
      containers:
      - name: vault
        image: hashicorp/vault:latest
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: "root"
        ports:
        - containerPort: 8200
